name: Kwiki-TimeZone
version: 0.10
abstract: Kwiki Time Zone Plugin
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.32
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
